// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RegistroPrioridades.DAL;

#nullable disable

namespace RegistroPrioridades.Migrations
{
    [DbContext(typeof(Contexto))]
    [Migration("20240910003559_Contexto_completo")]
    partial class Contexto_completo
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.4");

            modelBuilder.Entity("RegistroPrioridades.Models.Availability", b =>
                {
                    b.Property<int>("AvailabilityId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AvailabilityType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("AvailabilityId")
                        .HasName("PK__Availabi__DA3979B1DFA9D056");

                    b.HasIndex(new[] { "AvailabilityType" }, "UQ__Availabi__AF78582AF5049A9C")
                        .IsUnique();

                    b.ToTable("Availability");
                });

            modelBuilder.Entity("RegistroPrioridades.Models.Certifications", b =>
                {
                    b.Property<int>("CertificationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CertificationName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<string>("CredentialId")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("CredentialUrl")
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<DateOnly?>("ExpirationDate")
                        .HasColumnType("TEXT");

                    b.Property<DateOnly?>("IssueDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("IssuingOrganization")
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<int?>("ProfileId")
                        .HasColumnType("INTEGER");

                    b.HasKey("CertificationId")
                        .HasName("PK__Certific__1237E58AE2306722");

                    b.HasIndex("ProfileId");

                    b.ToTable("Certifications");
                });

            modelBuilder.Entity("RegistroPrioridades.Models.CompanyProfiles", b =>
                {
                    b.Property<int>("CompanyId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CompanyName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<string>("Industry")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Website")
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.HasKey("CompanyId")
                        .HasName("PK__CompanyP__2D971CAC66B3E5FD");

                    b.HasIndex("UserId");

                    b.ToTable("CompanyProfiles");
                });

            modelBuilder.Entity("RegistroPrioridades.Models.Education", b =>
                {
                    b.Property<int>("EducationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Degree")
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<DateOnly?>("EndDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("FieldOfStudy")
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<string>("InstitutionName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<int?>("ProfileId")
                        .HasColumnType("INTEGER");

                    b.Property<DateOnly?>("StartDate")
                        .HasColumnType("TEXT");

                    b.HasKey("EducationId")
                        .HasName("PK__Educatio__4BBE38050FD5C6ED");

                    b.HasIndex("ProfileId");

                    b.ToTable("Education");
                });

            modelBuilder.Entity("RegistroPrioridades.Models.JobApplications", b =>
                {
                    b.Property<int>("ApplicationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("ApplicationDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("CoverLetter")
                        .HasColumnType("TEXT");

                    b.Property<int>("JobOfferId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ProfileId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("ApplicationId")
                        .HasName("PK__JobAppli__C93A4C99F531AC3F");

                    b.HasIndex("JobOfferId");

                    b.HasIndex("ProfileId");

                    b.ToTable("JobApplications");
                });

            modelBuilder.Entity("RegistroPrioridades.Models.JobOffers", b =>
                {
                    b.Property<int>("JobOfferId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CompanyId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Currency")
                        .HasMaxLength(10)
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("ExpirationDate")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(true);

                    b.Property<string>("JobType")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("Location")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("PostedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<decimal?>("SalaryRangeMax")
                        .HasColumnType("decimal(10, 2)");

                    b.Property<decimal?>("SalaryRangeMin")
                        .HasColumnType("decimal(10, 2)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<int?>("WorkTypeId")
                        .HasColumnType("INTEGER");

                    b.HasKey("JobOfferId")
                        .HasName("PK__JobOffer__5B32794DD5D83230");

                    b.HasIndex("CompanyId");

                    b.HasIndex("WorkTypeId");

                    b.ToTable("JobOffers");
                });

            modelBuilder.Entity("RegistroPrioridades.Models.JobSkillRequirements", b =>
                {
                    b.Property<int>("JobSkillReqId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsRequired")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(true);

                    b.Property<int?>("JobOfferId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("RequiredLevel")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("SkillId")
                        .HasColumnType("INTEGER");

                    b.HasKey("JobSkillReqId")
                        .HasName("PK__JobSkill__9685A56A44B15020");

                    b.HasIndex("JobOfferId");

                    b.HasIndex("SkillId");

                    b.ToTable("JobSkillRequirements");
                });

            modelBuilder.Entity("RegistroPrioridades.Models.Languages", b =>
                {
                    b.Property<int>("LanguageId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("LanguageName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("LanguageId")
                        .HasName("PK__Language__B93855ABFC102DD2");

                    b.HasIndex(new[] { "LanguageName" }, "UQ__Language__E89C4A6AF31DE079")
                        .IsUnique();

                    b.ToTable("Languages");
                });

            modelBuilder.Entity("RegistroPrioridades.Models.PreferredWorkType", b =>
                {
                    b.Property<int>("WorkTypeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("WorkTypeName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("WorkTypeId")
                        .HasName("PK__Preferre__CCC06D2098F48FFF");

                    b.HasIndex(new[] { "WorkTypeName" }, "UQ__Preferre__4C45DD915E616D8D")
                        .IsUnique();

                    b.ToTable("PreferredWorkType");
                });

            modelBuilder.Entity("RegistroPrioridades.Models.Prioridades", b =>
                {
                    b.Property<int>("PrioridadId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("DiasCompromiso")
                        .HasColumnType("INTEGER");

                    b.HasKey("PrioridadId");

                    b.ToTable("Prioridades");
                });

            modelBuilder.Entity("RegistroPrioridades.Models.SkillCategory", b =>
                {
                    b.Property<int>("CategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CategoryName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("CategoryId")
                        .HasName("PK__SkillCat__19093A0BAAEC6961");

                    b.HasIndex(new[] { "CategoryName" }, "UQ__SkillCat__8517B2E0AD612525")
                        .IsUnique();

                    b.ToTable("SkillCategory");
                });

            modelBuilder.Entity("RegistroPrioridades.Models.Skills", b =>
                {
                    b.Property<int>("SkillId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("CategoryId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SkillName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("SkillId")
                        .HasName("PK__Skills__DFA09187BF73FFB2");

                    b.HasIndex("CategoryId");

                    b.HasIndex(new[] { "SkillName" }, "UQ__Skills__B63C657179F210A0")
                        .IsUnique();

                    b.ToTable("Skills");
                });

            modelBuilder.Entity("RegistroPrioridades.Models.UserLanguages", b =>
                {
                    b.Property<int>("UserLanguageId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("LanguageId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ProficiencyLevel")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<int?>("ProfileId")
                        .HasColumnType("INTEGER");

                    b.HasKey("UserLanguageId")
                        .HasName("PK__UserLang__8086CE39FFCBE055");

                    b.HasIndex("LanguageId");

                    b.HasIndex("ProfileId");

                    b.ToTable("UserLanguages");
                });

            modelBuilder.Entity("RegistroPrioridades.Models.UserProfiles", b =>
                {
                    b.Property<int>("ProfileId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("AvailabilityId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Biography")
                        .HasColumnType("TEXT");

                    b.Property<string>("Currency")
                        .HasMaxLength(10)
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("DesiredSalary")
                        .HasColumnType("decimal(10, 2)");

                    b.Property<string>("Email")
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("GitHubProfile")
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("LinkedInProfile")
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<string>("Location")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Phone")
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("PortfolioUrl")
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("WorkTypeId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("YearsOfExperience")
                        .HasColumnType("INTEGER");

                    b.HasKey("ProfileId")
                        .HasName("PK__UserProf__290C88E412B6A8C3");

                    b.HasIndex("AvailabilityId");

                    b.HasIndex("UserId");

                    b.HasIndex("WorkTypeId");

                    b.ToTable("UserProfiles");
                });

            modelBuilder.Entity("RegistroPrioridades.Models.UserSkills", b =>
                {
                    b.Property<int>("UserSkillId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsPrimary")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("ProfileId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("SkillId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("SkillLevel")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("YearsOfExperience")
                        .HasColumnType("INTEGER");

                    b.HasKey("UserSkillId")
                        .HasName("PK__UserSkil__2F28BE56474887EF");

                    b.HasIndex("ProfileId");

                    b.HasIndex("SkillId");

                    b.ToTable("UserSkills");
                });

            modelBuilder.Entity("RegistroPrioridades.Models.Users", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("LastLogin")
                        .HasColumnType("TEXT");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<string>("UserType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("UserId")
                        .HasName("PK__Users__1788CC4CE9E3C269");

                    b.HasIndex(new[] { "Email" }, "UQ__Users__A9D1053416007C50")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("RegistroPrioridades.Models.WorkExperience", b =>
                {
                    b.Property<int>("ExperienceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CompanyName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<DateOnly?>("EndDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("JobTitle")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<int?>("ProfileId")
                        .HasColumnType("INTEGER");

                    b.Property<DateOnly?>("StartDate")
                        .HasColumnType("TEXT");

                    b.HasKey("ExperienceId")
                        .HasName("PK__WorkExpe__2F4E3449351807F6");

                    b.HasIndex("ProfileId");

                    b.ToTable("WorkExperience");
                });

            modelBuilder.Entity("RegistroPrioridades.Models.Certifications", b =>
                {
                    b.HasOne("RegistroPrioridades.Models.UserProfiles", "Profile")
                        .WithMany("Certifications")
                        .HasForeignKey("ProfileId")
                        .HasConstraintName("FK__Certifica__Profi__44FF419A");

                    b.Navigation("Profile");
                });

            modelBuilder.Entity("RegistroPrioridades.Models.CompanyProfiles", b =>
                {
                    b.HasOne("RegistroPrioridades.Models.Users", "User")
                        .WithMany("CompanyProfiles")
                        .HasForeignKey("UserId")
                        .IsRequired()
                        .HasConstraintName("FK__CompanyPr__UserI__4D94879B");

                    b.Navigation("User");
                });

            modelBuilder.Entity("RegistroPrioridades.Models.Education", b =>
                {
                    b.HasOne("RegistroPrioridades.Models.UserProfiles", "Profile")
                        .WithMany("Education")
                        .HasForeignKey("ProfileId")
                        .HasConstraintName("FK__Education__Profi__4AB81AF0");

                    b.Navigation("Profile");
                });

            modelBuilder.Entity("RegistroPrioridades.Models.JobApplications", b =>
                {
                    b.HasOne("RegistroPrioridades.Models.JobOffers", "JobOffer")
                        .WithMany("JobApplications")
                        .HasForeignKey("JobOfferId")
                        .IsRequired()
                        .HasConstraintName("FK__JobApplic__JobOf__5BE2A6F2");

                    b.HasOne("RegistroPrioridades.Models.UserProfiles", "Profile")
                        .WithMany("JobApplications")
                        .HasForeignKey("ProfileId")
                        .IsRequired()
                        .HasConstraintName("FK__JobApplic__Profi__5CD6CB2B");

                    b.Navigation("JobOffer");

                    b.Navigation("Profile");
                });

            modelBuilder.Entity("RegistroPrioridades.Models.JobOffers", b =>
                {
                    b.HasOne("RegistroPrioridades.Models.CompanyProfiles", "Company")
                        .WithMany("JobOffers")
                        .HasForeignKey("CompanyId")
                        .IsRequired()
                        .HasConstraintName("FK__JobOffers__Compa__52593CB8");

                    b.HasOne("RegistroPrioridades.Models.PreferredWorkType", "WorkType")
                        .WithMany("JobOffers")
                        .HasForeignKey("WorkTypeId")
                        .HasConstraintName("FK__JobOffers__WorkT__534D60F1");

                    b.Navigation("Company");

                    b.Navigation("WorkType");
                });

            modelBuilder.Entity("RegistroPrioridades.Models.JobSkillRequirements", b =>
                {
                    b.HasOne("RegistroPrioridades.Models.JobOffers", "JobOffer")
                        .WithMany("JobSkillRequirements")
                        .HasForeignKey("JobOfferId")
                        .HasConstraintName("FK__JobSkillR__JobOf__571DF1D5");

                    b.HasOne("RegistroPrioridades.Models.Skills", "Skill")
                        .WithMany("JobSkillRequirements")
                        .HasForeignKey("SkillId")
                        .HasConstraintName("FK__JobSkillR__Skill__5812160E");

                    b.Navigation("JobOffer");

                    b.Navigation("Skill");
                });

            modelBuilder.Entity("RegistroPrioridades.Models.Skills", b =>
                {
                    b.HasOne("RegistroPrioridades.Models.SkillCategory", "Category")
                        .WithMany("Skills")
                        .HasForeignKey("CategoryId")
                        .HasConstraintName("FK__Skills__Category__36B12243");

                    b.Navigation("Category");
                });

            modelBuilder.Entity("RegistroPrioridades.Models.UserLanguages", b =>
                {
                    b.HasOne("RegistroPrioridades.Models.Languages", "Language")
                        .WithMany("UserLanguages")
                        .HasForeignKey("LanguageId")
                        .HasConstraintName("FK__UserLangu__Langu__4222D4EF");

                    b.HasOne("RegistroPrioridades.Models.UserProfiles", "Profile")
                        .WithMany("UserLanguages")
                        .HasForeignKey("ProfileId")
                        .HasConstraintName("FK__UserLangu__Profi__412EB0B6");

                    b.Navigation("Language");

                    b.Navigation("Profile");
                });

            modelBuilder.Entity("RegistroPrioridades.Models.UserProfiles", b =>
                {
                    b.HasOne("RegistroPrioridades.Models.Availability", "Availability")
                        .WithMany("UserProfiles")
                        .HasForeignKey("AvailabilityId")
                        .HasConstraintName("FK__UserProfi__Avail__2F10007B");

                    b.HasOne("RegistroPrioridades.Models.Users", "User")
                        .WithMany("UserProfiles")
                        .HasForeignKey("UserId")
                        .IsRequired()
                        .HasConstraintName("FK__UserProfi__UserI__2E1BDC42");

                    b.HasOne("RegistroPrioridades.Models.PreferredWorkType", "WorkType")
                        .WithMany("UserProfiles")
                        .HasForeignKey("WorkTypeId")
                        .HasConstraintName("FK__UserProfi__WorkT__300424B4");

                    b.Navigation("Availability");

                    b.Navigation("User");

                    b.Navigation("WorkType");
                });

            modelBuilder.Entity("RegistroPrioridades.Models.UserSkills", b =>
                {
                    b.HasOne("RegistroPrioridades.Models.UserProfiles", "Profile")
                        .WithMany("UserSkills")
                        .HasForeignKey("ProfileId")
                        .HasConstraintName("FK__UserSkill__Profi__3A81B327");

                    b.HasOne("RegistroPrioridades.Models.Skills", "Skill")
                        .WithMany("UserSkills")
                        .HasForeignKey("SkillId")
                        .HasConstraintName("FK__UserSkill__Skill__3B75D760");

                    b.Navigation("Profile");

                    b.Navigation("Skill");
                });

            modelBuilder.Entity("RegistroPrioridades.Models.WorkExperience", b =>
                {
                    b.HasOne("RegistroPrioridades.Models.UserProfiles", "Profile")
                        .WithMany("WorkExperience")
                        .HasForeignKey("ProfileId")
                        .HasConstraintName("FK__WorkExper__Profi__47DBAE45");

                    b.Navigation("Profile");
                });

            modelBuilder.Entity("RegistroPrioridades.Models.Availability", b =>
                {
                    b.Navigation("UserProfiles");
                });

            modelBuilder.Entity("RegistroPrioridades.Models.CompanyProfiles", b =>
                {
                    b.Navigation("JobOffers");
                });

            modelBuilder.Entity("RegistroPrioridades.Models.JobOffers", b =>
                {
                    b.Navigation("JobApplications");

                    b.Navigation("JobSkillRequirements");
                });

            modelBuilder.Entity("RegistroPrioridades.Models.Languages", b =>
                {
                    b.Navigation("UserLanguages");
                });

            modelBuilder.Entity("RegistroPrioridades.Models.PreferredWorkType", b =>
                {
                    b.Navigation("JobOffers");

                    b.Navigation("UserProfiles");
                });

            modelBuilder.Entity("RegistroPrioridades.Models.SkillCategory", b =>
                {
                    b.Navigation("Skills");
                });

            modelBuilder.Entity("RegistroPrioridades.Models.Skills", b =>
                {
                    b.Navigation("JobSkillRequirements");

                    b.Navigation("UserSkills");
                });

            modelBuilder.Entity("RegistroPrioridades.Models.UserProfiles", b =>
                {
                    b.Navigation("Certifications");

                    b.Navigation("Education");

                    b.Navigation("JobApplications");

                    b.Navigation("UserLanguages");

                    b.Navigation("UserSkills");

                    b.Navigation("WorkExperience");
                });

            modelBuilder.Entity("RegistroPrioridades.Models.Users", b =>
                {
                    b.Navigation("CompanyProfiles");

                    b.Navigation("UserProfiles");
                });
#pragma warning restore 612, 618
        }
    }
}
